package dal;
// default package
// Generated 27.04.2014 17:42:05 by Hibernate Tools 4.0.0

/**
 * Containerrequested generated by hbm2java
 */
public class Containerrequested implements java.io.Serializable {

	private Long id;
	private Workflowrun workflowrun;
	private long amount;

	public Containerrequested() {
	}

	public Containerrequested(Workflowrun workflowrun, long amount) {
		this.workflowrun = workflowrun;
		this.amount = amount;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Workflowrun getWorkflowrun() {
		return this.workflowrun;
	}

	public void setWorkflowrun(Workflowrun workflowrun) {
		this.workflowrun = workflowrun;
	}

	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

}
