package dal;

// Generated 27.04.2014 18:21:34 by Hibernate Tools 3.4.0.CR1

/**
 * Containerfinished generated by hbm2java
 */
public class Containerfinished implements java.io.Serializable {

	private Long id;
	private Workflowrun workflowrun;
	private long amount;

	public Containerfinished() {
	}

	public Containerfinished(Workflowrun workflowrun, long amount) {
		this.workflowrun = workflowrun;
		this.amount = amount;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Workflowrun getWorkflowrun() {
		return this.workflowrun;
	}

	public void setWorkflowrun(Workflowrun workflowrun) {
		this.workflowrun = workflowrun;
	}

	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

}
