package dal;
// default package
// Generated 27.04.2014 17:42:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Filestagingevent generated by hbm2java
 */
public class Filestagingevent implements java.io.Serializable {

	private Long id;
	private Invocation invocation;
	private String name;
	private boolean in;
	private Long size;
	private Set<Timestat> timestats = new HashSet<Timestat>(0);

	public Filestagingevent() {
	}

	public Filestagingevent(Invocation invocation, boolean in) {
		this.invocation = invocation;
		this.in = in;
	}

	public Filestagingevent(Invocation invocation, String name, boolean in,
			Long size, Set<Timestat> timestats) {
		this.invocation = invocation;
		this.name = name;
		this.in = in;
		this.size = size;
		this.timestats = timestats;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Invocation getInvocation() {
		return this.invocation;
	}

	public void setInvocation(Invocation invocation) {
		this.invocation = invocation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isIn() {
		return this.in;
	}

	public void setIn(boolean in) {
		this.in = in;
	}

	public Long getSize() {
		return this.size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	public Set<Timestat> getTimestats() {
		return this.timestats;
	}

	public void setTimestats(Set<Timestat> timestats) {
		this.timestats = timestats;
	}

}
