package dal;
// default package
// Generated 27.04.2014 17:42:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Stagingevent generated by hbm2java
 */
public class Stagingevent implements java.io.Serializable {

	private Long id;
	private Invocation invocation;
	private boolean in;
	private Set<Timestat> timestats = new HashSet<Timestat>(0);

	public Stagingevent() {
	}

	public Stagingevent(Invocation invocation, boolean in) {
		this.invocation = invocation;
		this.in = in;
	}

	public Stagingevent(Invocation invocation, boolean in,
			Set<Timestat> timestats) {
		this.invocation = invocation;
		this.in = in;
		this.timestats = timestats;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Invocation getInvocation() {
		return this.invocation;
	}

	public void setInvocation(Invocation invocation) {
		this.invocation = invocation;
	}

	public boolean isIn() {
		return this.in;
	}

	public void setIn(boolean in) {
		this.in = in;
	}

	public Set<Timestat> getTimestats() {
		return this.timestats;
	}

	public void setTimestats(Set<Timestat> timestats) {
		this.timestats = timestats;
	}

}
