package dal;

// Generated 27.04.2014 18:21:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Workflowrun generated by hbm2java
 */
@Entity
public class Workflowrun implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	private String runId;
	private String wfName;
	private Long wfTime;
//	private Set<Containerfinished> containerfinisheds = new HashSet<Containerfinished>(
//			0);
//	private Set<Containerallocated> containerallocateds = new HashSet<Containerallocated>(
//			0);
//	private Set<Containerrequested> containerrequesteds = new HashSet<Containerrequested>(
//			0);

	@OneToMany(mappedBy="workflowrun")
	private Set<WorkflowrunHasTask> workflowrunHasTasks = new HashSet<WorkflowrunHasTask>(
			0);
	
	public Workflowrun() {
	}

	public Workflowrun(String runId) {
		this.runId = runId;
	}

	public Workflowrun(String runId, String wfName, Long wfTime,
			//Set<Containerfinished> containerfinisheds,
			//Set<Containerallocated> containerallocateds,
			//Set<Containerrequested> containerrequesteds
			Set<WorkflowrunHasTask> workflowrunHasTasks		) {
		this.runId = runId;
		this.wfName = wfName;
		this.wfTime = wfTime;
		//this.containerfinisheds = containerfinisheds;
		//this.containerallocateds = containerallocateds;
		this.workflowrunHasTasks = workflowrunHasTasks;
		//this.containerrequesteds = containerrequesteds;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRunId() {
		return this.runId;
	}

	public void setRunId(String runId) {
		this.runId = runId;
	}

	public String getWfName() {
		return this.wfName;
	}

	public void setWfName(String wfName) {
		this.wfName = wfName;
	}

	public Long getWfTime() {
		return this.wfTime;
	}

	public void setWfTime(Long wfTime) {
		this.wfTime = wfTime;
	}

//	public Set<Containerfinished> getContainerfinisheds() {
//		return this.containerfinisheds;
//	}
//
//	public void setContainerfinisheds(Set<Containerfinished> containerfinisheds) {
//		this.containerfinisheds = containerfinisheds;
//	}
//
//	public Set<Containerallocated> getContainerallocateds() {
//		return this.containerallocateds;
//	}
//
//	public void setContainerallocateds(
//			Set<Containerallocated> containerallocateds) {
//		this.containerallocateds = containerallocateds;
//	}

	public Set<WorkflowrunHasTask> getWorkflowrunHasTasks() {
		return this.workflowrunHasTasks;
	}

	public void setWorkflowrunHasTasks(
			Set<WorkflowrunHasTask> workflowrunHasTasks) {
		this.workflowrunHasTasks = workflowrunHasTasks;
	}

//	public Set<Containerrequested> getContainerrequesteds() {
//		return this.containerrequesteds;
//	}
//
//	public void setContainerrequesteds(
//			Set<Containerrequested> containerrequesteds) {
//		this.containerrequesteds = containerrequesteds;
//	}

}
