package dal;

// Generated 27.04.2014 18:21:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;

import java.util.Set;

/**
 * WorkflowrunHasTask generated by hbm2java
 */
@Entity
public class WorkflowrunHasTask implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private String id;
	
	@ManyToOne
	@JoinColumn(name = "workflowrun_fk")
	private Workflowrun workflowrun;

	@ManyToOne
	@JoinColumn(name = "task_fk")
	private Task task;

	@OneToMany
	private Set<Invocation> invocations = new HashSet<Invocation>(0);

	public WorkflowrunHasTask() {
	}

	public WorkflowrunHasTask(String id, Workflowrun workflowrun, Task task) {
		this.id = id;
		this.workflowrun = workflowrun;
		this.task = task;
	}

	public WorkflowrunHasTask(String id, Workflowrun workflowrun, Task task,
			Set<Invocation> invocations) {
		this.id = id;
		this.workflowrun = workflowrun;
		this.task = task;
		this.invocations = invocations;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Workflowrun getWorkflowrun() {
		return this.workflowrun;
	}

	public void setWorkflowrun(Workflowrun workflowrun) {
		this.workflowrun = workflowrun;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Set<Invocation> getInvocations() {
		return this.invocations;
	}

	public void setInvocations(Set<Invocation> invocations) {
		this.invocations = invocations;
	}

}
