// default package
// Generated 27.04.2014 17:42:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Workflowrun generated by hbm2java
 */
public class Workflowrun implements java.io.Serializable {

	private Long id;
	private String runId;
	private String wfName;
	private Long wfTime;
	private Set<Containerfinished> containerfinisheds = new HashSet<Containerfinished>(
			0);
	private Set<Containerallocated> containerallocateds = new HashSet<Containerallocated>(
			0);
	private Set<WorkflowrunHasTask> workflowrunHasTasks = new HashSet<WorkflowrunHasTask>(
			0);
	private Set<Containerrequested> containerrequesteds = new HashSet<Containerrequested>(
			0);

	public Workflowrun() {
	}

	public Workflowrun(String runId) {
		this.runId = runId;
	}

	public Workflowrun(String runId, String wfName, Long wfTime,
			Set<Containerfinished> containerfinisheds,
			Set<Containerallocated> containerallocateds,
			Set<WorkflowrunHasTask> workflowrunHasTasks,
			Set<Containerrequested> containerrequesteds) {
		this.runId = runId;
		this.wfName = wfName;
		this.wfTime = wfTime;
		this.containerfinisheds = containerfinisheds;
		this.containerallocateds = containerallocateds;
		this.workflowrunHasTasks = workflowrunHasTasks;
		this.containerrequesteds = containerrequesteds;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRunId() {
		return this.runId;
	}

	public void setRunId(String runId) {
		this.runId = runId;
	}

	public String getWfName() {
		return this.wfName;
	}

	public void setWfName(String wfName) {
		this.wfName = wfName;
	}

	public Long getWfTime() {
		return this.wfTime;
	}

	public void setWfTime(Long wfTime) {
		this.wfTime = wfTime;
	}

	public Set<Containerfinished> getContainerfinisheds() {
		return this.containerfinisheds;
	}

	public void setContainerfinisheds(Set<Containerfinished> containerfinisheds) {
		this.containerfinisheds = containerfinisheds;
	}

	public Set<Containerallocated> getContainerallocateds() {
		return this.containerallocateds;
	}

	public void setContainerallocateds(
			Set<Containerallocated> containerallocateds) {
		this.containerallocateds = containerallocateds;
	}

	public Set<WorkflowrunHasTask> getWorkflowrunHasTasks() {
		return this.workflowrunHasTasks;
	}

	public void setWorkflowrunHasTasks(
			Set<WorkflowrunHasTask> workflowrunHasTasks) {
		this.workflowrunHasTasks = workflowrunHasTasks;
	}

	public Set<Containerrequested> getContainerrequesteds() {
		return this.containerrequesteds;
	}

	public void setContainerrequesteds(
			Set<Containerrequested> containerrequesteds) {
		this.containerrequesteds = containerrequesteds;
	}

}
