package de.huberlin.hiwaydb.dal;

//Generated 19.05.2014 12:56:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import de.huberlin.hiwaydb.dal.Invocation;
import de.huberlin.hiwaydb.dal.Timestat;

/**
* File generated by hbm2java
*/
@Entity
public class File implements java.io.Serializable {

	@Id @GeneratedValue
	private Long id;
	@ManyToOne
	private Invocation invocation;
	private String name;
	private Long size;
	@OneToMany(mappedBy="filestagingevent")
	private Set<Timestat> timestats = new HashSet<Timestat>(0);

	public File() {
	}

	public File(Invocation invocation, String name) {
		this.invocation = invocation;
		this.name = name;
	}

	public File(Invocation invocation, String name, Long size,
			Set<Timestat> timestats) {
		this.invocation = invocation;
		this.name = name;
		this.size = size;
		this.timestats = timestats;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Invocation getInvocation() {
		return this.invocation;
	}

	public void setInvocation(Invocation invocation) {
		this.invocation = invocation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getSize() {
		return this.size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	public Set<Timestat> getTimestats() {
		return this.timestats;
	}

	public void setTimestats(Set<Timestat> timestats) {
		this.timestats = timestats;
	}

}
