package de.huberlin.hiwaydb.dal;

// Generated 19.05.2014 12:56:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Invocation generated by hbm2java
 */
@Entity
public class Invocation implements java.io.Serializable {

	@Id
	private long invocationId;
	@ManyToOne
	private Task task;
	@ManyToOne
	private Workflowrun workflowrun;
	
	private String hostname;
	private Long scheduleTime;
	private String standardOut;
	private String standardError;
	
	@OneToMany(mappedBy="invocation")
	private Set<Inoutput> inoutputs = new HashSet<Inoutput>(0);
	@OneToMany(mappedBy="invocation")
	private Set<File> files = new HashSet<File>(0);
	@OneToMany(mappedBy="invocation")
	private Set<Timestat> timestats = new HashSet<Timestat>(0);
	@OneToMany(mappedBy="invocation")
	private Set<Userevent> userevents = new HashSet<Userevent>(0);

	public Invocation() {
	}

	public Invocation(long invocationId, Task task, Workflowrun workflowrun) {
		this.invocationId = invocationId;
		this.task = task;
		this.workflowrun = workflowrun;
	}

	public Invocation(long invocationId, Task task, Workflowrun workflowrun,
			String hostname, Long scheduleTime, String standardOut,
			String standardError, Set<Inoutput> inoutputs, Set<File> files,
			Set<Timestat> timestats, Set<Userevent> userevents) {
		this.invocationId = invocationId;
		this.task = task;
		this.workflowrun = workflowrun;
		this.hostname = hostname;
		this.scheduleTime = scheduleTime;
		this.standardOut = standardOut;
		this.standardError = standardError;
		this.inoutputs = inoutputs;
		this.files = files;
		this.timestats = timestats;
		this.userevents = userevents;
	}

	public long getInvocationId() {
		return this.invocationId;
	}

	public void setInvocationId(long invocationId) {
		this.invocationId = invocationId;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Workflowrun getWorkflowrun() {
		return this.workflowrun;
	}

	public void setWorkflowrun(Workflowrun workflowrun) {
		this.workflowrun = workflowrun;
	}

	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	public Long getScheduleTime() {
		return this.scheduleTime;
	}

	public void setScheduleTime(Long scheduleTime) {
		this.scheduleTime = scheduleTime;
	}

	public String getStandardOut() {
		return this.standardOut;
	}

	public void setStandardOut(String standardOut) {
		this.standardOut = standardOut;
	}

	public String getStandardError() {
		return this.standardError;
	}

	public void setStandardError(String standardError) {
		this.standardError = standardError;
	}

	public Set<Inoutput> getInoutputs() {
		return this.inoutputs;
	}

	public void setInoutputs(Set<Inoutput> inoutputs) {
		this.inoutputs = inoutputs;
	}

	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	public Set<Timestat> getTimestats() {
		return this.timestats;
	}

	public void setTimestats(Set<Timestat> timestats) {
		this.timestats = timestats;
	}

	public Set<Userevent> getUserevents() {
		return this.userevents;
	}

	public void setUserevents(Set<Userevent> userevents) {
		this.userevents = userevents;
	}

}
