package de.huberlin.hiwaydb.dal;

// Generated 19.05.2014 12:56:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Invocation generated by hbm2java
 */
@Entity
public class Invocation implements java.io.Serializable {

	@Id
	@GeneratedValue
	private Long id;
	private Long invocationid;
	@ManyToOne
	private Task task;
	@ManyToOne
	private Workflowrun workflowrun;

	private String hostname;
	private Long scheduleTime;
	private String standardout;
	private String standarderror;

	private Long realtime;
	private Long realtimein;
	private Long realtimeout;
	private Date didon;

	@OneToMany(mappedBy = "invocation")
	private Set<Inoutput> inoutputs = new HashSet<Inoutput>(0);
	@OneToMany(mappedBy = "invocation")
	private Set<File> files = new HashSet<File>(0);
	@OneToMany(mappedBy = "invocation")
	private Set<Userevent> userevents = new HashSet<Userevent>(0);

	public Invocation() {
	}

	public Invocation(long invocationId, Task task, Workflowrun workflowrun) {
		this.invocationid = invocationId;
		this.task = task;
		this.workflowrun = workflowrun;
	}

	public Invocation(long invocationid, Task task, Workflowrun workflowrun,
			String hostname, Long scheduleTime, String standardOut,
			String standardError, Set<Inoutput> inoutputs, Set<File> files,
			Set<Userevent> userevents, Long realTime, Long realtimein,
			Long realtimeout, Date didon) {
		this.invocationid = invocationid;
		this.task = task;
		this.workflowrun = workflowrun;
		this.hostname = hostname;
		this.scheduleTime = scheduleTime;
		this.standardout = standardOut;
		this.standarderror = standardError;
		this.inoutputs = inoutputs;
		this.files = files;
		this.userevents = userevents;
		this.realtime = realTime;
		this.realtimein = realtimein;
		this.realtimeout = realtimeout;
		this.didon = didon;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getInvocationId() {
		return this.invocationid;
	}

	public void setInvocationId(long invocationId) {
		this.invocationid = invocationId;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Workflowrun getWorkflowrun() {
		return this.workflowrun;
	}

	public void setWorkflowrun(Workflowrun workflowrun) {
		this.workflowrun = workflowrun;
	}

	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	public Long getScheduleTime() {
		return this.scheduleTime;
	}

	public void setScheduleTime(Long scheduleTime) {
		this.scheduleTime = scheduleTime;
	}

	public String getStandardOut() {
		return this.standardout;
	}

	public void setStandardOut(String standardOut) {
		this.standardout = standardOut;
	}

	public String getStandardError() {
		return this.standarderror;
	}

	public void setStandardError(String standardError) {
		this.standarderror = standardError;
	}

	public Set<Inoutput> getInoutputs() {
		return this.inoutputs;
	}

	public void setInoutputs(Set<Inoutput> inoutputs) {
		this.inoutputs = inoutputs;
	}

	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	public Set<Userevent> getUserevents() {
		return this.userevents;
	}

	public void setUserevents(Set<Userevent> userevents) {
		this.userevents = userevents;
	}

	public Long getRealTime() {
		return this.realtime;
	}

	public void setRealTime(Long realTime) {
		this.realtime = realTime;
	}

	public Long getRealTimeIn() {
		return this.realtimein;
	}

	public void setRealTimeIn(Long realtimein) {
		this.realtimein = realtimein;
	}

	public Long getRealTimeOut() {
		return this.realtimeout;
	}

	public void setRealTimeOut(Long realtimeout) {
		this.realtimeout = realtimeout;
	}

	public Date getDidOn() {
		return this.didon;
	}

	public void setDidOn(Date didon) {
		this.didon = didon;
	}

}
