package de.huberlin.hiwaydb.dal;

import javax.persistence.*;
/**
 * Output generated by hbm2java
 */
@Entity
public class Output implements java.io.Serializable {

	@Id @GeneratedValue
	private Long id;
	@ManyToOne
	private Invocation invocation;
	private String key;
	private String content;

	public Output() {
	}

	public Output(Invocation invocation, String key, String content) {
		this.invocation = invocation;
		this.key = key;
		this.content = content;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Invocation getInvocation() {
		return this.invocation;
	}

	public void setInvocation(Invocation invocation) {
		this.invocation = invocation;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
