package de.huberlin.hiwaydb.dal;

import javax.persistence.*;
/**
 * Output generated by hbm2java
 */
@Entity
public class Output implements java.io.Serializable {

	@Id @GeneratedValue
	private Long id;
	@ManyToOne
	private Invocation invocation;
	private String keypart;
	private String content;

	public Output() {
	}

	public Output(Invocation invocation, String keypart, String content) {
		this.invocation = invocation;
		this.keypart = keypart;
		this.content = content;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Invocation getInvocation() {
		return this.invocation;
	}

	public void setInvocation(Invocation invocation) {
		this.invocation = invocation;
	}

	public String getKeypart() {
		return this.keypart;
	}

	public void setKeypart(String keypart) {
		this.keypart = keypart;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
