package de.huberlin.hiwaydb.dal;
// Generated 02.05.2014 17:34:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
/**
 * Stagingevent generated by hbm2java
 */
@Entity
public class Stagingevent implements java.io.Serializable {

	@Id @GeneratedValue
	private Long id;
	@ManyToOne
	private Invocation invocation;
	private boolean inevent;
	
	@OneToMany(mappedBy="stagingevent")
	private Set<Timestat> timestats = new HashSet<Timestat>(0);
	

	public Stagingevent() {
	}

	public Stagingevent(Invocation invocation, boolean inEvent) {
		this.invocation = invocation;
		this.inevent = inEvent;
	}

	public Stagingevent(Invocation invocation, boolean inEvent, Set timestats) {
		this.invocation = invocation;
		this.inevent = inEvent;
		this.timestats = timestats;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Invocation getInvocation() {
		return this.invocation;
	}

	public void setInvocation(Invocation invocation) {
		this.invocation = invocation;
	}

	public boolean isinEvent() {
		return this.inevent;
	}

	public void setinEvent(boolean inEvent) {
		this.inevent = inEvent;
	}

	public Set getTimestats() {
		return this.timestats;
	}

	public void setTimestats(Set timestats) {
		this.timestats = timestats;
	}

}
