package de.huberlin.hiwaydb.dal;
// Generated 02.05.2014 17:34:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;

import javax.persistence.*;

import dal.WorkflowrunHasTask;

import java.util.Set;

/**
 * Workflowrun generated by hbm2java
 */
@Entity
public class Workflowrun implements java.io.Serializable {

	@Id @GeneratedValue
	private Long id;
	private String runId;
	private String wfName;
	private Long wfTime;
	
//	@OneToMany(mappedBy="workflowrun")
//	private Set<WorkflowrunHasTask> workflowrunHasTasks = new HashSet<WorkflowrunHasTask>(
//			0);
	
	@OneToMany(mappedBy="workflowrun")
	private Set<Invocation> invocations = new HashSet<Invocation>(0);

	public Workflowrun() {
	}

	public Workflowrun(String runId) {
		this.runId = runId;
	}

	public Workflowrun(String runId, String wfName, Long wfTime, Set invocations) {
		this.runId = runId;
		this.wfName = wfName;
		this.wfTime = wfTime;
		this.invocations = invocations;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRunId() {
		return this.runId;
	}

	public void setRunId(String runId) {
		this.runId = runId;
	}

	public String getWfName() {
		return this.wfName;
	}

	public void setWfName(String wfName) {
		this.wfName = wfName;
	}

	public Long getWfTime() {
		return this.wfTime;
	}

	public void setWfTime(Long wfTime) {
		this.wfTime = wfTime;
	}

	public Set getInvocations() {
		return this.invocations;
	}

	public void setInvocations(Set invocations) {
		this.invocations = invocations;
	}

}
