package de.huberlin.hiwaydb.dal;

// Generated 19.05.2014 12:56:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Workflowrun generated by hbm2java
 */
@Entity
public class Workflowrun implements java.io.Serializable {

	@Id @GeneratedValue
	private Long id;
	private String runId;
	private String wfName;
	private Long wfTime;
	@OneToMany(mappedBy="workflowrun")
	private Set<Hiwayevent> hiwayevents = new HashSet<Hiwayevent>(0);
	@OneToMany(mappedBy="workflowrun")
	private Set<Invocation> invocations = new HashSet<Invocation>(0);

	public Workflowrun() {
	}

	public Workflowrun(String runId) {
		this.runId = runId;
	}

	public Workflowrun(String runId, String wfName, Long wfTime,
			Set<Hiwayevent> hiwayevents, Set<Invocation> invocations) {
		this.runId = runId;
		this.wfName = wfName;
		this.wfTime = wfTime;
		this.hiwayevents = hiwayevents;
		this.invocations = invocations;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRunId() {
		return this.runId;
	}

	public void setRunId(String runId) {
		this.runId = runId;
	}

	public String getWfName() {
		return this.wfName;
	}

	public void setWfName(String wfName) {
		this.wfName = wfName;
	}

	public Long getWfTime() {
		return this.wfTime;
	}

	public void setWfTime(Long wfTime) {
		this.wfTime = wfTime;
	}

	public Set<Hiwayevent> getHiwayevents() {
		return this.hiwayevents;
	}

	public void setHiwayevents(Set<Hiwayevent> hiwayevents) {
		this.hiwayevents = hiwayevents;
	}

	public Set<Invocation> getInvocations() {
		return this.invocations;
	}

	public void setInvocations(Set<Invocation> invocations) {
		this.invocations = invocations;
	}

}
