package de.huberlin.hiwaydb.dal;

// Generated 19.05.2014 12:56:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Workflowrun generated by hbm2java
 */
@Entity
public class Workflowrun implements java.io.Serializable {

	@Id @GeneratedValue
	private Long id;
	private String runid;
	private String wfname;
	private Long wftime;
	@OneToMany(mappedBy="workflowrun")
	private Set<Hiwayevent> hiwayevents = new HashSet<Hiwayevent>(0);
	@OneToMany(mappedBy="workflowrun")
	private Set<Invocation> invocations = new HashSet<Invocation>(0);

	public Workflowrun() {
	}

	public Workflowrun(String runid) {
		this.runid = runid;
	}

	public Workflowrun(String runid, String wfname, Long wftime,
			Set<Hiwayevent> hiwayevents, Set<Invocation> invocations) {
		this.runid = runid;
		this.wfname = wfname;
		this.wftime = wftime;
		this.hiwayevents = hiwayevents;
		this.invocations = invocations;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRunId() {
		return this.runid;
	}

	public void setRunId(String runid) {
		this.runid = runid;
	}

	public String getWfName() {
		return this.wfname;
	}

	public void setWfName(String wfname) {
		this.wfname = wfname;
	}

	public Long getWfTime() {
		return this.wftime;
	}

	public void setWfTime(Long wftime) {
		this.wftime = wftime;
	}

	public Set<Hiwayevent> getHiwayevents() {
		return this.hiwayevents;
	}

	public void setHiwayevents(Set<Hiwayevent> hiwayevents) {
		this.hiwayevents = hiwayevents;
	}

	public Set<Invocation> getInvocations() {
		return this.invocations;
	}

	public void setInvocations(Set<Invocation> invocations) {
		this.invocations = invocations;
	}

}
