SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `messungen` ;
CREATE SCHEMA IF NOT EXISTS `messungen` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `messungen` ;

CREATE TABLE `messungen`.`accesstime` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funktion` VARCHAR(100) NULL,
  `input` VARCHAR(100) NULL,
  `tick` BIGINT UNSIGNED NULL,
  `tock` BIGINT UNSIGNED NULL,
  `ticktockdif` BIGINT UNSIGNED NULL,
  `dbvolume` BIGINT UNSIGNED NULL,
  `returnvolume` BIGINT UNSIGNED NULL,
   `runId` VARCHAR(100) NULL,
   `key` VARCHAR(100) NULL,
   `config` VARCHAR(45) NULL,
      `wfName` VARCHAR(100) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
